# Generated by Django 3.1 on 2021-01-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Last Name')),
                ('avatar', models.ImageField(blank=True, upload_to='teachers/avatar/', verbose_name='Profile picture')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number')),
                ('room_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Room number')),
                ('subject_taught', models.CharField(blank=True, max_length=512, null=True, verbose_name='Subject Taught')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TeacherBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('csv_file', models.FileField(upload_to='teachers/bulkupload/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
